name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test -v ./...

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
        VERSION: ${{ github.ref_name }}
      run: |
        BINARY_NAME="money-${{ matrix.goos }}-${{ matrix.goarch }}"
        go build -v -ldflags="-s -w -X 'github.com/arjungandhi/money/pkg/version.Version=$VERSION'" -o "${BINARY_NAME}" ./cmd/money

    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: money-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: money-${{ matrix.goos }}-${{ matrix.goarch }}
        tag: ${{ github.ref }}
        overwrite: true